# Generated by Django 4.1.5 on 2023-01-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('userpass', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('price', models.IntegerField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='product_images')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
